### ISSUE TITLE
Assessment Results

### ISSUE THREAD

**Issue by damwhit** [dcoleman21/mod_0_skills#1]
@dcoleman21 overall, nice work on the assessment. Because you've been in good standing up until this point on assignments, I'd like to give you the opportunity to make some changes to your assessment, before we declare you `technical ready`:
* [x] Please update part 3 (make sure that you're testing your code in irb.
  * here are the directions: https://fierce-beyond-34376.herokuapp.com/confirmation
* [x] In part 2, your class 1 make_square method mentions a round attribute? 
  * I think `round` makes sense for a boolean attribute, but shape does not. 
  * either update the attribute name you're using, or change shape to a string.
* [x] Make sure that array attributes are named plurally
* [x] Make sure to use action like names for your methods. 
  * If I see `is_` prefix something that makes me think that it’s an attribute

**Comment by dcoleman21** [comment]
@damwhit thank you for the feedback and the opportunity to make the above mentioned changes. All changes should be complete and available for review. Please let me know how else I can get better with all of this.

**Comment by damwhit** [comment]
@dcoleman21 this is looking much better.. However, I'd like you to make some additional updates:
* [x] In your class 1 and class 1 example object files, change your `square` attribute to `round` (since that's the attribute your reference in your `make_square` method)
  * [x] How does that effect the result of your make_square method? - please show in the example object file
* [x] Make sure that the methods you're using in your example object files have been defined in the appropriate class file
* [x] what would be a better name for the temperature attribute in class2 and class2 example object? Please make that change.

**Comment by dcoleman21** [comment]
> @dcoleman21 this is looking much better.. However, I'd like you to make some additional updates:
> 
> * [x]  In your class 1 and class 1 example object files, change your `square` attribute to `round` (since that's the attribute your reference in your `make_square` method)
>   
>   * [x]  How does that effect the result of your make_square method? - please show in the example object file
@damwhit it would make the make_square method: round: false because the round attribute = false since I want a square table. 
> * [x]  Make sure that the methods you're using in your example object files have been defined in the appropriate class file
> * [x]  what would be a better name for the temperature attribute in class2 and class2 example object? Please make that change.

**Comment by dcoleman21** [comment]
Additional updates have been made. I think I maybe got it this time. I was also wondering if you offer mentoring?

**Comment by damwhit** [comment]
@dcoleman21 I think things look good for the most part. I thought spicy might be a better name for an attribute that is affected by make_spicy. And I love that you changed the name of your array attribute for class 2 to be plural.
As far as mentoring goes, we do offer it. I'll reach out to Emma to see if she can pair you up with someone!
